In [1]:
import torch

In [4]:
input_dim = 5 
hidden_dim = 20

directions = torch.randn(20, 5)

data = []

# Number of iterations (you have 1 in your loop)
iterations = 1

# Generate data
for i in range(iterations):
    indices = torch.randperm(20)[:2]
    acts = (torch.randint(1, 5, (2,1)) * directions[indices]).sum(dim=0)
    torch.randint(1, 5, (2,1))
    print(acts)
    data.append(acts)

data = torch.stack(data)

Original Data:
 tensor([[-3.1030e-01, -1.6470e+00,  4.5091e-01, -1.1697e-01, -1.4581e+00,
          7.6753e-01,  3.8782e-03,  3.1881e-01,  9.2598e-01, -2.1881e+00,
         -5.7923e-01, -1.7414e-01,  1.2539e+00,  4.0965e-01,  6.6474e-01,
          6.6729e-01,  1.0672e+00,  3.0346e-02, -2.8022e+00,  6.8279e-01],
        [ 1.1605e+00, -1.2718e+00, -1.0683e+00, -2.3624e+00, -1.1677e-01,
         -5.3067e-01, -1.3805e-01,  7.7235e-01, -6.3577e-01,  5.6742e-02,
          1.5165e-01, -4.6011e-01,  1.2317e+00,  1.3338e-01,  3.3431e-01,
         -1.6804e+00, -1.8275e+00, -3.1565e-01, -1.8458e+00, -8.7156e-01],
        [-2.2397e-01, -1.3969e-01, -7.3504e-01, -3.3715e-01, -1.6030e-01,
          5.4118e-01, -4.5679e-01,  7.1031e-01, -7.3113e-01, -3.3855e-01,
          8.1303e-01,  7.1675e-01,  1.1092e+00,  2.4312e-01,  2.0001e+00,
          8.7684e-01, -2.8066e-01,  1.4278e+00, -4.6657e-01,  8.1917e-01],
        [-7.8624e-01, -2.1341e+00, -2.8370e-01,  8.2322e-01,  2.9648e-01,
         -2.2878e-0

In [18]:
import torch

directions = torch.randn(20, 5)

data = []

# Number of iterations (you have 1 in your loop)
iterations = 1000

# Generate data
for i in range(iterations):
    indices = torch.randperm(20)[:2]
    acts = (torch.rand(2, 1) * directions[indices]).sum(dim=0)
    data.append(acts)

data = torch.stack(data)

print(data)

    


tensor([[-1.7919,  0.0399, -2.7106,  0.0215, -2.4740],
        [ 0.2484, -0.2741, -0.0690,  0.3431, -0.3945],
        [-0.2959, -0.2431,  0.0114,  0.3957,  0.5150],
        ...,
        [ 0.0107,  0.5316, -2.0169, -0.3293,  0.1706],
        [-0.1964, -0.0560,  0.3996,  1.3557, -1.0923],
        [-0.3544,  0.5206,  0.3322,  0.4037, -0.8753]])


In [13]:
torch.rand(1)

tensor([0.4956])

In [56]:
def get_norms(data):
    norms = torch.norm(data, dim=1)
    return norms

a = torch.rand(1000, 50)

In [61]:
torch.randint(0,5,)

tensor([[0.0195],
        [0.2434]])

In [52]:
(a[1]).norm()

tensor(3.9502)

In [59]:
b = a *4 / get_norms(a).mean()

In [60]:
get_norms(b).mean()

tensor(4.)