In [1]:
import torch

In [2]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)



In [5]:
((a-b)**2).mean(dim = 1)

tensor([0.1141, 0.5042])

In [10]:
((a-b)**2).mean(dim = 1).mean(dim=0)

tensor(0.3092)

In [9]:
(a[-1]-b[-1])**2

tensor([0.4882, 0.9506, 0.0739])

In [12]:
c = (a-b)**2

In [17]:
c , a,b

(tensor([[0.1354, 0.1129, 0.0939],
         [0.4882, 0.9506, 0.0739]]),
 tensor([[0.4936, 0.6357, 0.3064],
         [0.1524, 0.0018, 0.0600]]),
 tensor([[0.8615, 0.2996, 0.6128],
         [0.8511, 0.9768, 0.3318]]))

In [14]:
c.mean()

tensor(0.3092)

In [19]:
c.sum(dim =1).mean(dim=0)

tensor(0.9275)

In [20]:
((a-b)**2).sum(dim=1)/(a-b).size(0)

tensor([0.1711, 0.7564])

In [23]:
((a-b)**2).sum()/(a-b).size(0)

tensor(0.9275)

In [24]:
from torch.nn.functional import mse_loss
mse_loss(a,b)

tensor(0.3092)

In [25]:
dataset_size = a.size(0)
    
    # Reconstruction loss
recon_loss = torch.sum((a - b) ** 2) / dataset_size

In [26]:
recon_loss

tensor(0.9275)

In [27]:
d = torch.rand(2, 3)

In [28]:
d

tensor([[0.9583, 0.0489, 0.5821],
        [0.5455, 0.3955, 0.2502]])

In [35]:
torch.sum((a - b) ** 2)/2

tensor(0.9275)

In [30]:
(a - b) ** 2

tensor([[0.1354, 0.1129, 0.0939],
        [0.4882, 0.9506, 0.0739]])

In [31]:
torch.sum((a - b) ** 2)

tensor(1.8549)

In [34]:
((a - b) ** 2).sum(-1).mean(0)

tensor(0.9275)

In [37]:
((a-b)**2).sum(dim = -1)

tensor([0.3422, 1.5127])

In [39]:
((a-b)**2).sum(dim = -1).mean(dim = 0)

tensor(0.9275)

In [40]:
torch.mean(torch.sum((a - b) ** 2, dim=1))

tensor(0.9275)

In [41]:
encoded = torch.rand(2, 10)
w_d = torch.rand(10, 3)

In [43]:
dec = torch.nn.Linear(10,3)
wd = dec.weight

In [45]:
wd.shape, encoded.shape

(torch.Size([3, 10]), torch.Size([2, 10]))

In [49]:
wd, encoded

(Parameter containing:
 tensor([[-0.2975, -0.3147, -0.3140,  0.1149, -0.0415,  0.1374, -0.0331,  0.2342,
          -0.2663,  0.2907],
         [-0.2691,  0.1487, -0.2609, -0.0719, -0.3087,  0.2872,  0.0692,  0.2532,
          -0.1344, -0.0544],
         [-0.2889,  0.2134,  0.0890, -0.2151, -0.0801,  0.2786,  0.0188, -0.0006,
           0.1623, -0.0603]], requires_grad=True),
 tensor([[0.9571, 0.7930, 0.6742, 0.9741, 0.9389, 0.7626, 0.5013, 0.6155, 0.5596,
          0.0567],
         [0.7877, 0.8524, 0.8207, 0.2832, 0.8648, 0.5919, 0.4381, 0.3084, 0.2437,
          0.4849]]))

In [46]:
torch.sum(torch.norm(encoded, dim=0) * torch.norm(wd, dim=1))

RuntimeError: The size of tensor a (10) must match the size of tensor b (3) at non-singleton dimension 0

In [62]:
wd.shape

torch.Size([3, 10])

In [51]:
torch.norm(encoded, dim=0, p= 0)

tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [52]:
encoded

tensor([[0.9571, 0.7930, 0.6742, 0.9741, 0.9389, 0.7626, 0.5013, 0.6155, 0.5596,
         0.0567],
        [0.7877, 0.8524, 0.8207, 0.2832, 0.8648, 0.5919, 0.4381, 0.3084, 0.2437,
         0.4849]])

In [56]:
wd[:,1].norm(2)

tensor(0.4083, grad_fn=<LinalgVectorNormBackward0>)

In [58]:
torch.norm(wd[:,1], p =2)

tensor(0.4083, grad_fn=<LinalgVectorNormBackward0>)

In [59]:
torch.norm(wd, p=2, dim=0)

tensor([0.4944, 0.4083, 0.4178, 0.2542, 0.3216, 0.4231, 0.0789, 0.3449, 0.3396,
        0.3019], grad_fn=<LinalgVectorNormBackward0>)

In [61]:
encoded*torch.norm(wd, p=2, dim=0)

tensor([[0.4732, 0.3238, 0.2817, 0.2477, 0.3019, 0.3226, 0.0396, 0.2123, 0.1901,
         0.0171],
        [0.3894, 0.3480, 0.3429, 0.0720, 0.2781, 0.2504, 0.0346, 0.1064, 0.0827,
         0.1464]], grad_fn=<MulBackward0>)

In [63]:
encoded

tensor([[0.9571, 0.7930, 0.6742, 0.9741, 0.9389, 0.7626, 0.5013, 0.6155, 0.5596,
         0.0567],
        [0.7877, 0.8524, 0.8207, 0.2832, 0.8648, 0.5919, 0.4381, 0.3084, 0.2437,
         0.4849]])

In [64]:
torch.norm(wd, p=2, dim=0)

tensor([0.4944, 0.4083, 0.4178, 0.2542, 0.3216, 0.4231, 0.0789, 0.3449, 0.3396,
        0.3019], grad_fn=<LinalgVectorNormBackward0>)

In [66]:
torch.sum(torch.norm(wd, p=2, dim=0)*encoded)

tensor(4.4609, grad_fn=<SumBackward0>)

In [70]:
(torch.norm(wd, p=2, dim=0)*encoded).sum(dim=-1)

tensor([2.4099, 2.0510], grad_fn=<SumBackward1>)

In [71]:
torch.sum((a-b)**2)

tensor(1.8549)

In [76]:
((a-b)**2).sum(dim = 1).sum(dim =0)

tensor(1.8549)

In [81]:
(torch.norm(wd, p=2, dim=0)*encoded.abs()).sum(dim = 1).sum(dim = 0)

tensor(4.4609, grad_fn=<SumBackward1>)

In [80]:
torch.sum(torch.norm(wd, p=2, dim=0)*encoded)

tensor(4.4609, grad_fn=<SumBackward0>)