In [1]:
import torch

In [65]:
input_dim = 5 
hidden_dim = 20

directions = torch.randn(20, 5)

data = []

# Number of iterations (you have 1 in your loop)
iterations = 1

# Generate data
for i in range(iterations):
    indices = torch.randperm(20)[:2]
    acts = (torch.randint(-2, 2, (2,1)) * directions[indices]).sum(dim=0)
    torch.randint(1, 5, (2,1))
    print(acts)
    data.append(acts)

data = torch.stack(data)

tensor([0.5460, 3.4554, 1.1096, 3.7744, 0.3267])


In [18]:
import torch

directions = torch.randn(20, 5)

data = []

# Number of iterations (you have 1 in your loop)
iterations = 1000

# Generate data
for i in range(iterations):
    indices = torch.randperm(20)[:2]
    acts = (torch.rand(2, 1) * directions[indices]).sum(dim=0)
    data.append(acts)

data = torch.stack(data)

print(data)

    


tensor([[-1.7919,  0.0399, -2.7106,  0.0215, -2.4740],
        [ 0.2484, -0.2741, -0.0690,  0.3431, -0.3945],
        [-0.2959, -0.2431,  0.0114,  0.3957,  0.5150],
        ...,
        [ 0.0107,  0.5316, -2.0169, -0.3293,  0.1706],
        [-0.1964, -0.0560,  0.3996,  1.3557, -1.0923],
        [-0.3544,  0.5206,  0.3322,  0.4037, -0.8753]])


In [13]:
torch.rand(1)

tensor([0.4956])

In [56]:
def get_norms(data):
    norms = torch.norm(data, dim=1)
    return norms

a = torch.rand(1000, 50)

In [61]:
torch.randint(0,5,)

tensor([[0.0195],
        [0.2434]])

In [52]:
(a[1]).norm()

tensor(3.9502)

In [59]:
b = a *4 / get_norms(a).mean()

In [60]:
get_norms(b).mean()

tensor(4.)

In [69]:
a.shape

torch.Size([1000, 50])

In [68]:
a.nonzero().shape

torch.Size([50000, 2])

In [74]:
(a > 0).count_nonzero()

tensor(50000)

In [84]:
a = torch.rand(3,4,5)

In [78]:
a =torch.rand(5,5)

In [91]:
a.norm(p = 0, dim =1).shape

torch.Size([3, 5])

In [83]:
a.norm(0, dim = 1, keepdim=True).mean()

tensor(5.)

In [92]:
a = torch.arange(500)
dataloader = torch.utils.data.DataLoader(a, batch_size=10, shuffle=True)
    

In [96]:
next(iter(dataloader))

tensor([283, 300, 409, 323, 160, 175, 332, 126, 250, 185])

In [97]:
a = torch.nn.Linear(3,4)

In [98]:
a.weight.shape

torch.Size([4, 3])

In [114]:
a = torch.nn.Linear(input_dim, hidden_dim, bias=False)
torch.nn.init.kaiming_uniform(a.weight)

/var/folders/_j/ctxbrk0926zg7z8n7jc3xpp00000gn/T/ipykernel_63550/3980150713.py:2: UserWarning: nn.init.kaiming_uniform is now deprecated in favor of nn.init.kaiming_uniform_.
  torch.nn.init.kaiming_uniform(a.weight)


Parameter containing:
tensor([[ 1.0375, -0.9804, -0.5230, -0.2980,  0.0527],
        [-0.9422, -0.7669,  0.1702,  0.2368, -0.1794],
        [ 0.0464,  0.4118, -1.0425,  1.0280,  0.2374],
        [-0.8938, -0.9331,  0.6838, -0.1038, -0.2335],
        [ 0.1422,  0.8353, -0.4228,  0.6198, -0.2090],
        [-0.6194,  0.1338, -0.3348,  0.3124,  0.9862],
        [-0.4427, -0.8882,  0.8092, -0.3222,  0.6503],
        [-0.7298,  0.8772,  0.1578,  0.1790, -0.5427],
        [-0.6765,  0.5439,  0.4853,  0.5846, -0.0637],
        [-0.4687,  0.0499,  0.4601,  0.5414,  0.8911],
        [-0.4095, -0.8846,  0.4845,  0.2652, -0.8610],
        [ 0.7428, -0.9464,  0.9416,  0.7025,  0.9572],
        [ 0.5764, -0.0705,  0.7041,  0.1877,  0.3671],
        [ 1.0069, -0.9735,  0.4193,  0.5997, -0.0547],
        [-0.3697,  0.8581,  0.8432, -1.0792, -0.8243],
        [ 0.3495, -0.6567, -0.2900,  1.0557, -1.0494],
        [-0.8581,  0.7756, -0.4250,  0.9974,  1.0438],
        [ 0.9572, -0.6510,  0.8448, -0.7406

In [1]:
a

NameError: name 'a' is not defined

In [115]:
w = a.weight.data

In [116]:
w.norm(dim = 0)

tensor([3.2203, 3.2386, 2.7968, 2.6972, 3.0512])

In [112]:
norm = 0.1*self.decoder.weight.norm(p=2, dim=0, keepdim=True)
decoder.weight.div_(norm)

torch.Size([20, 5])

In [140]:
from torch.utils.data import DataLoader, SubsetRandomSampler

a = torch.arange(10)
sampler = SubsetRandomSampler(a, num_samples=5)
dataloader = DataLoader(a, sampler= sampler)

for i in range(10):
    print(next(iter(dataloader)))

TypeError: SubsetRandomSampler.__init__() got an unexpected keyword argument 'num_samples'

In [157]:
import torch
from torch.utils.data import DataLoader, SequentialSampler

a = torch.arange(10,20)
sampler = SequentialSampler(a, replacement=False, num_samples=5)
dataloader = DataLoader(a, sampler=sampler, batch_size=5)

for i in range(10):
    print(next(iter(dataloader)))


TypeError: SequentialSampler.__init__() got an unexpected keyword argument 'replacement'

In [141]:
torch.stack(a,2)

TypeError: stack(): argument 'tensors' (position 1) must be tuple of Tensors, not Tensor

In [146]:
torch.randint(1,100, (5,))

tensor([90,  6,  5, 45, 11])

In [147]:
torch.randperm(100)

tensor([56,  7, 23, 22, 38, 20,  2, 40, 66, 32,  4,  8,  1, 95, 48, 17,  3, 70,
        76, 80, 35, 75, 16, 42,  0, 86, 60,  9, 73,  5, 19, 67, 83, 82, 43, 11,
        78, 49, 36, 21, 34, 69, 74, 79, 52, 10, 47, 61, 62, 84, 50, 37, 24, 98,
        65, 93, 99, 46, 71, 59, 88, 97, 45, 92, 13, 85, 91, 25, 31, 39, 87, 18,
        14, 30, 81, 64, 90, 29, 72, 27, 28, 53, 94, 96, 63, 44, 41,  6, 55, 77,
        58, 68, 33, 26, 51, 54, 57, 89, 15, 12])

In [168]:
a = torch.arange(20,50)

In [170]:
dataloader = iter(DataLoader(a, shuffle= True, batch_size=5))

for i in range(10):
    data = next(dataloader)
    print(data)

tensor([44, 29, 40, 26, 41])
tensor([21, 49, 23, 38, 32])
tensor([37, 35, 25, 34, 20])
tensor([46, 39, 27, 48, 22])
tensor([42, 36, 43, 24, 45])
tensor([30, 33, 47, 31, 28])


StopIteration: 

In [154]:
dataloader = iter(DataLoader(a, shuffle= True, batch_size=5))

for i in range(10):
    data = next(dataloader)
    print(data)

tensor([20, 21, 22, 23, 24])

In [161]:
it = iter(dataloader)
first = next(it)
second = next(it)

In [162]:
first

tensor([10, 11, 12, 13, 14])

In [163]:
second

tensor([15, 16, 17, 18, 19])

In [2]:
import torch

In [10]:
a = torch.zeros(5)

In [11]:
a

tensor([0., 0., 0., 0., 0.])

In [15]:
b = a.clone().detach()

In [16]:
b

tensor([0., 0., 0., 0., 0.])

In [18]:
b[0] =1

In [19]:
b

tensor([1., 0., 0., 0., 0.])

In [22]:
a=a

In [24]:
a+a

tensor([0., 0., 0., 0., 0.])

In [3]:
from torch.utils.data import DataLoader, RandomSampler

dataset = torch.arange(50,100)

data_loader = DataLoader(dataset, batch_size=32, sampler=RandomSampler(dataset, replacement=True))

iter = iter(data_loader)

for i in range(10):
    print(next(iter))


TypeError: '_SingleProcessDataLoaderIter' object is not callable